server:
  port: 8000
spring.groovy.template.cache: false
logging.level.org.springframework.web: DEBUG

conference:
  yegor256.url: http://localhost:8001
  jbaruch.url: http://localhost:8002

tokens:
  jbaruch: npm leftpad artifactory артифактори groovy груви nexus нексус телефон binary repository manager бинарный репозиторий зависимостей барух jbaruch
  yegor256: ооп oop java джава жава жаба annotation annotations аннотации аннотация spring спринг декоратор decorator объекты объект object книги книга книги книгу книгах почитать читать голые данные классы класс stackoverflow google электронные женщины дамы девушки девушках дамах дизайн дизайны паттерн паттерны декоратор декораторы orm орм

assistant.default:
  answers:
    - когда Николай Алименков уйдет из Епама, он будет отвечать на подобные вопросы
    - одному лишь богу ведом ответ
    - даже егор не знает ответа на этот вопрос
    - ты шутишь? Даже дети знают ответ на этот вопрос!
    - ты бы еще про семантику volatile спросил!

logging.level:
  org.springframework.test.context.cache: debug
debug: true
